apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-backend
  template:
    metadata:
      labels:
        app: fortune-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/casperf18/simple-fortune-cookie-group12-backend:latest
          ports:
            - containerPort: 9000
          env:
            - name: REDIS_DNS
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: fortune-backend
  ports:
    - port: 9000
      targetPort: 9000